// Generated by gencpp from file robot_msgs/PTZ_perception.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_PTZ_PERCEPTION_H
#define ROBOT_MSGS_MESSAGE_PTZ_PERCEPTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace robot_msgs
{
template <class ContainerAllocator>
struct PTZ_perception_
{
  typedef PTZ_perception_<ContainerAllocator> Type;

  PTZ_perception_()
    : header()
    , track_id(0)
    , yaw(0.0)
    , pitch(0.0)
    , score(0)
    , target_lock(0)
    , spin_state(0)
    , fire_command(0)
    , fire_mode(0)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  PTZ_perception_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , track_id(0)
    , yaw(0.0)
    , pitch(0.0)
    , score(0)
    , target_lock(0)
    , spin_state(0)
    , fire_command(0)
    , fire_mode(0)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _track_id_type;
  _track_id_type track_id;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef float _pitch_type;
  _pitch_type pitch;

   typedef int8_t _score_type;
  _score_type score;

   typedef int8_t _target_lock_type;
  _target_lock_type target_lock;

   typedef int8_t _spin_state_type;
  _spin_state_type spin_state;

   typedef int8_t _fire_command_type;
  _fire_command_type fire_command;

   typedef int8_t _fire_mode_type;
  _fire_mode_type fire_mode;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::robot_msgs::PTZ_perception_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::PTZ_perception_<ContainerAllocator> const> ConstPtr;

}; // struct PTZ_perception_

typedef ::robot_msgs::PTZ_perception_<std::allocator<void> > PTZ_perception;

typedef boost::shared_ptr< ::robot_msgs::PTZ_perception > PTZ_perceptionPtr;
typedef boost::shared_ptr< ::robot_msgs::PTZ_perception const> PTZ_perceptionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::PTZ_perception_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::PTZ_perception_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::PTZ_perception_<ContainerAllocator1> & lhs, const ::robot_msgs::PTZ_perception_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.track_id == rhs.track_id &&
    lhs.yaw == rhs.yaw &&
    lhs.pitch == rhs.pitch &&
    lhs.score == rhs.score &&
    lhs.target_lock == rhs.target_lock &&
    lhs.spin_state == rhs.spin_state &&
    lhs.fire_command == rhs.fire_command &&
    lhs.fire_mode == rhs.fire_mode &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::PTZ_perception_<ContainerAllocator1> & lhs, const ::robot_msgs::PTZ_perception_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::PTZ_perception_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::PTZ_perception_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::PTZ_perception_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::PTZ_perception_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::PTZ_perception_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::PTZ_perception_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::PTZ_perception_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b2635782c4d3d935ef69981c3144d66c";
  }

  static const char* value(const ::robot_msgs::PTZ_perception_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb2635782c4d3d935ULL;
  static const uint64_t static_value2 = 0xef69981c3144d66cULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::PTZ_perception_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/PTZ_perception";
  }

  static const char* value(const ::robot_msgs::PTZ_perception_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::PTZ_perception_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int8 track_id\n"
"float32 yaw\n"
"float32 pitch\n"
"int8 score\n"
"int8 target_lock\n"
"int8 spin_state\n"
"int8 fire_command\n"
"int8 fire_mode\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::robot_msgs::PTZ_perception_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::PTZ_perception_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.track_id);
      stream.next(m.yaw);
      stream.next(m.pitch);
      stream.next(m.score);
      stream.next(m.target_lock);
      stream.next(m.spin_state);
      stream.next(m.fire_command);
      stream.next(m.fire_mode);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PTZ_perception_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::PTZ_perception_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::PTZ_perception_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "track_id: ";
    Printer<int8_t>::stream(s, indent + "  ", v.track_id);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "score: ";
    Printer<int8_t>::stream(s, indent + "  ", v.score);
    s << indent << "target_lock: ";
    Printer<int8_t>::stream(s, indent + "  ", v.target_lock);
    s << indent << "spin_state: ";
    Printer<int8_t>::stream(s, indent + "  ", v.spin_state);
    s << indent << "fire_command: ";
    Printer<int8_t>::stream(s, indent + "  ", v.fire_command);
    s << indent << "fire_mode: ";
    Printer<int8_t>::stream(s, indent + "  ", v.fire_mode);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_PTZ_PERCEPTION_H
