// Generated by gencpp from file robot_msgs/robot_ctrl.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_ROBOT_CTRL_H
#define ROBOT_MSGS_MESSAGE_ROBOT_CTRL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace robot_msgs
{
template <class ContainerAllocator>
struct robot_ctrl_
{
  typedef robot_ctrl_<ContainerAllocator> Type;

  robot_ctrl_()
    : header()
    , yaw(0.0)
    , pitch(0.0)
    , fire_command(0)
    , fire_mode(0)
    , is_follow(0)  {
    }
  robot_ctrl_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , yaw(0.0)
    , pitch(0.0)
    , fire_command(0)
    , fire_mode(0)
    , is_follow(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef float _pitch_type;
  _pitch_type pitch;

   typedef int8_t _fire_command_type;
  _fire_command_type fire_command;

   typedef int8_t _fire_mode_type;
  _fire_mode_type fire_mode;

   typedef int8_t _is_follow_type;
  _is_follow_type is_follow;





  typedef boost::shared_ptr< ::robot_msgs::robot_ctrl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::robot_ctrl_<ContainerAllocator> const> ConstPtr;

}; // struct robot_ctrl_

typedef ::robot_msgs::robot_ctrl_<std::allocator<void> > robot_ctrl;

typedef boost::shared_ptr< ::robot_msgs::robot_ctrl > robot_ctrlPtr;
typedef boost::shared_ptr< ::robot_msgs::robot_ctrl const> robot_ctrlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::robot_ctrl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::robot_ctrl_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::robot_ctrl_<ContainerAllocator1> & lhs, const ::robot_msgs::robot_ctrl_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.yaw == rhs.yaw &&
    lhs.pitch == rhs.pitch &&
    lhs.fire_command == rhs.fire_command &&
    lhs.fire_mode == rhs.fire_mode &&
    lhs.is_follow == rhs.is_follow;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::robot_ctrl_<ContainerAllocator1> & lhs, const ::robot_msgs::robot_ctrl_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::robot_ctrl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::robot_ctrl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::robot_ctrl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::robot_ctrl_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::robot_ctrl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::robot_ctrl_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::robot_ctrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d113cc45537caf169fa198ab9396ee38";
  }

  static const char* value(const ::robot_msgs::robot_ctrl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd113cc45537caf16ULL;
  static const uint64_t static_value2 = 0x9fa198ab9396ee38ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::robot_ctrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/robot_ctrl";
  }

  static const char* value(const ::robot_msgs::robot_ctrl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::robot_ctrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32 yaw\n"
"float32 pitch\n"
"int8 fire_command\n"
"int8 fire_mode\n"
"int8 is_follow\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::robot_msgs::robot_ctrl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::robot_ctrl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.yaw);
      stream.next(m.pitch);
      stream.next(m.fire_command);
      stream.next(m.fire_mode);
      stream.next(m.is_follow);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robot_ctrl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::robot_ctrl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::robot_ctrl_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "fire_command: ";
    Printer<int8_t>::stream(s, indent + "  ", v.fire_command);
    s << indent << "fire_mode: ";
    Printer<int8_t>::stream(s, indent + "  ", v.fire_mode);
    s << indent << "is_follow: ";
    Printer<int8_t>::stream(s, indent + "  ", v.is_follow);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_ROBOT_CTRL_H
