// Generated by gencpp from file robot_msgs/Track_reset.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_TRACK_RESET_H
#define ROBOT_MSGS_MESSAGE_TRACK_RESET_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace robot_msgs
{
template <class ContainerAllocator>
struct Track_reset_
{
  typedef Track_reset_<ContainerAllocator> Type;

  Track_reset_()
    : header()
    , Track_id(0)
    , Reset(0)  {
    }
  Track_reset_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , Track_id(0)
    , Reset(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _Track_id_type;
  _Track_id_type Track_id;

   typedef int8_t _Reset_type;
  _Reset_type Reset;





  typedef boost::shared_ptr< ::robot_msgs::Track_reset_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::Track_reset_<ContainerAllocator> const> ConstPtr;

}; // struct Track_reset_

typedef ::robot_msgs::Track_reset_<std::allocator<void> > Track_reset;

typedef boost::shared_ptr< ::robot_msgs::Track_reset > Track_resetPtr;
typedef boost::shared_ptr< ::robot_msgs::Track_reset const> Track_resetConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::Track_reset_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::Track_reset_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::Track_reset_<ContainerAllocator1> & lhs, const ::robot_msgs::Track_reset_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.Track_id == rhs.Track_id &&
    lhs.Reset == rhs.Reset;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::Track_reset_<ContainerAllocator1> & lhs, const ::robot_msgs::Track_reset_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::Track_reset_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::Track_reset_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::Track_reset_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::Track_reset_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::Track_reset_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::Track_reset_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::Track_reset_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c12ffa81e03dadac12770fb057786612";
  }

  static const char* value(const ::robot_msgs::Track_reset_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc12ffa81e03dadacULL;
  static const uint64_t static_value2 = 0x12770fb057786612ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::Track_reset_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/Track_reset";
  }

  static const char* value(const ::robot_msgs::Track_reset_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::Track_reset_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int8 Track_id\n"
"int8 Reset\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::robot_msgs::Track_reset_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::Track_reset_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.Track_id);
      stream.next(m.Reset);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Track_reset_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::Track_reset_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::Track_reset_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "Track_id: ";
    Printer<int8_t>::stream(s, indent + "  ", v.Track_id);
    s << indent << "Reset: ";
    Printer<int8_t>::stream(s, indent + "  ", v.Reset);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_TRACK_RESET_H
