// Generated by gencpp from file robot_msgs/usb_camera.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_USB_CAMERA_H
#define ROBOT_MSGS_MESSAGE_USB_CAMERA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace robot_msgs
{
template <class ContainerAllocator>
struct usb_camera_
{
  typedef usb_camera_<ContainerAllocator> Type;

  usb_camera_()
    : header()
    , target_lock(0)
    , track_id(0)
    , score(0)
    , yaw(0.0)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  usb_camera_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , target_lock(0)
    , track_id(0)
    , score(0)
    , yaw(0.0)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _target_lock_type;
  _target_lock_type target_lock;

   typedef int8_t _track_id_type;
  _track_id_type track_id;

   typedef int32_t _score_type;
  _score_type score;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::robot_msgs::usb_camera_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::usb_camera_<ContainerAllocator> const> ConstPtr;

}; // struct usb_camera_

typedef ::robot_msgs::usb_camera_<std::allocator<void> > usb_camera;

typedef boost::shared_ptr< ::robot_msgs::usb_camera > usb_cameraPtr;
typedef boost::shared_ptr< ::robot_msgs::usb_camera const> usb_cameraConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::usb_camera_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::usb_camera_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::usb_camera_<ContainerAllocator1> & lhs, const ::robot_msgs::usb_camera_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.target_lock == rhs.target_lock &&
    lhs.track_id == rhs.track_id &&
    lhs.score == rhs.score &&
    lhs.yaw == rhs.yaw &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::usb_camera_<ContainerAllocator1> & lhs, const ::robot_msgs::usb_camera_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::usb_camera_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::usb_camera_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::usb_camera_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::usb_camera_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::usb_camera_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::usb_camera_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::usb_camera_<ContainerAllocator> >
{
  static const char* value()
  {
    return "45d15251d30e3c161412211a669b38ba";
  }

  static const char* value(const ::robot_msgs::usb_camera_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x45d15251d30e3c16ULL;
  static const uint64_t static_value2 = 0x1412211a669b38baULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::usb_camera_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/usb_camera";
  }

  static const char* value(const ::robot_msgs::usb_camera_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::usb_camera_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int8 target_lock\n"
"int8 track_id\n"
"int32 score\n"
"float32 yaw\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::robot_msgs::usb_camera_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::usb_camera_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.target_lock);
      stream.next(m.track_id);
      stream.next(m.score);
      stream.next(m.yaw);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct usb_camera_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::usb_camera_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::usb_camera_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "target_lock: ";
    Printer<int8_t>::stream(s, indent + "  ", v.target_lock);
    s << indent << "track_id: ";
    Printer<int8_t>::stream(s, indent + "  ", v.track_id);
    s << indent << "score: ";
    Printer<int32_t>::stream(s, indent + "  ", v.score);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_USB_CAMERA_H
